const SUCCESS_ENUM = Object.freeze({
    CREATED: 'Created',
    OK: 'OK',
    NO_CONTENT: 'No Content',
    RESET_CONTENT: 'Reset Content',
    PARTIAL_CONTENT: 'Partial Content',
    MOVED_PERMANENTLY: 'Moved Permanently',
    FOUND: 'Found',
    SEE_OTHER: 'See Other',
    NOT_MODIFIED: 'Not Modified',
    TEMPORARY_REDIRECT: 'Temporary Redirect',
    PERMANENT_REDIRECT: 'Permanent Redirect',
});

const FAILLURE_ENUM = Object.freeze({
    BAD_REQUEST: 'Bad Request',
    NOT_FOUND: 'Not Found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN: 'Forbidden',
    CONFLICT: 'Conflict',
    GONE: 'Gone',
    PAYLOAD_TOO_LARGE: 'Payload Too Large',
    UNSUPPORTED_MEDIA_TYPE: 'Unsupported Media Type',
    UNPROCESSABLE_ENTITY: 'Unprocessable Entity',
    TOO_MANY_REQUESTS: 'Too Many Requests',
    REQUEST_TIMEOUT: 'Request Timeout',
    SERVICE_UNAVAILABLE: 'Service Unavailable',
    GATEWAY_TIMEOUT: 'Gateway Timeout',
    HTTP_VERSION_NOT_SUPPORTED: 'HTTP Version Not Supported',
    NETWORK_AUTHENTICATION_REQUIRED: 'Network Authentication Required',
    NOT_EXTENDED: 'Not Extended',
    PRECONDITION_FAILED: 'Precondition Failed',
    REQUEST_HEADER_FIELDS_TOO_LARGE: 'Request Header Fields Too Large',
    REQUEST_URI_TOO_LONG: 'Request-URI Too Long',
    REQUESTED_RANGE_NOT_SATISFIABLE: 'Requested Range Not Satisfiable',
    LENGTH_REQUIRED: 'Length Required',
    METHOD_NOT_ALLOWED: 'Method Not Allowed',
    PAYLOAD_TOO_LARGE: 'Payload Too Large',
    URI_TOO_LONG: 'URI Too Long',
    UNSUPPORTED_MEDIA_TYPE: 'Unsupported Media Type',
    UPGRADE_REQUIRED: 'Upgrade Required',
    PRECONDITION_REQUIRED: 'Precondition Required',
    TOO_MANY_REQUESTS: 'Too Many Requests',
    REQUEST_HEADER_FIELDS_TOO_LARGE: 'Request Header Fields Too Large',
    CONNECTION_TIMED_OUT: 'Connection Timed Out',
    NETWORK_READ_TIMEOUT: 'Network Read Timeout',
    NETWORK_CONNECT_TIMEOUT: 'Network Connect Timeout',
    NETWORK_CONNECTION_TIMEOUT: 'Network Connection Timeout',
    NETWORK_SOCKET_TIMEOUT: 'Network Socket Timeout',
    NETWORK_SOCKET_EXCEPTION: 'Network Socket Exception',
    NETWORK_SOCKET_ERROR: 'Network Socket Error',
    NETWORK_SOCKET_CLOSED: 'Network Socket Closed',
});

module.exports
module.exports = {
    SUCCESS_ENUM,
    FAILLURE_ENUM,
};